### ISSUE TITLE
Please add Description and Website in "About"

### ISSUE THREAD

**Issue by lzblack** [brandonchin00/OIM3690-01-Brandon-Chin-Project#1]

**Comment by brandonchin00** [comment]
Professor, I couldn't find where the about section was but my 
description for my website: Personal Portfolio Website for Brandon Chin.
Website link is: www.brandonchin.com.

**Comment by lzblack** [comment]
Here: 
![image](https://user-images.githubusercontent.com/1173076/199012394-f7c226bc-cd2f-4f7d-961e-3711c8786b6d.png)

**Comment by brandonchin00** [comment]
Got it! Thank you. All set
