### ISSUE TITLE
Peer Project Review

### ISSUE THREAD

**Issue by sherissacheng** [brandonchin00/OIM3690-01-Brandon-Chin-Project#2]
Hi Brandon, your website looks great! My suggestions are below:
**Content**
1. The color of your "Skillset" background is the same color as the navigation bar text, which means it disappears into the background when I scroll into that section. I'd suggest changing one of the colors to a deeper tone so that the text stands out!
2. Using bars to represent your skills is usually not recommended because what 45% means to you means differently to someone else. While using years to represent skillset isn't perfectly accurate either, it can give recruiters a better gauge of how well you understand a skill
**Technical**
1. I'm not sure I understand the use of "pre" under your index.html and whether it is necessary. Perhaps just adjusting the div itself in css could eliminate the use of the "pre"?
2. If you want to blend the harsh line between your cloud and your "Skillset" background, you could try `background-blend-mode: screen` and see if it blends!

**Comment by brandonchin00** [comment]
Your suggestions are great. I fixed the navbar color blending issue. I couldn't figure out a better measure to gauge skillset. So I decided to leave to be. It could represent my confidence in the skillset. Pre was a typo. Thank you for the catch. I'm not sure how background-blend-mode works but I'll try thank you.
