### ISSUE TITLE
Peer Project Review

### ISSUE THREAD

**Issue by Muegalue** [brandonchin00/OIM3690-01-Brandon-Chin-Project#3]
Hi Brandon, 

I think you did an amazing job on your project! I like how you were able to display many things but still keep it separated for the user to read. My suggestions would be...
1. In my opinion I think I see some disconnection as I scroll down your page. The space and the sky effect is really effective, but I think the connection between skillset, contact me and sitemap doesn't follow through.
2. In my understanding, one landing page should have one h1 and you can have multiple h2 or h3. I am not sure if this is relevant with the course, but in terms of SEO best practices, h1 should only be used once. 
3. I think you need to nest li within ol or ul. from what I understand, li is not allowed as an child element of div. 
4. There's an extra </div> end tags at line 105. 
I hope this helps, but other than this I think you're good!

**Comment by brandonchin00** [comment]
Awesome thank you for your suggestions. I fixed all your issues. I will also take advantage of the h1 suggestion. I was not aware of that!
